// SPDX-License-Identifier: MIT
package assemble

import (
	"fmt"
	"go/format"
	"sort"
	"strconv"
	"strings"
)

func Generate(m *Manifest, toolchain bool) ([]byte, error) {
	var s strings.Builder
	s.WriteString("// Code generated by Wippy Builder. DO NOT EDIT.\n// SPDX-License-Identifier: MIT\npackage main\nimport (\n\"github.com/wippyai/runtime/api/boot\"\n")
	if toolchain {
		s.WriteString("\"context\"\n\"fmt\"\n\"os\"\n\"path/filepath\"\n\"github.com/wippyai/runtime/cmd/wippy/cmd\"\n")
	} else {
		s.WriteString("_ \"embed\"\napp \"github.com/wippyai/runtime/cmd/app\"\n")
	}
	var components []string
	host := "nil"
	for i, n := range m.Native {
		fmt.Fprintf(&s, "native%d %q\n", i, n.Package)
		component := fmt.Sprintf("component%d", i)
		components = append(components, component)
		if n.Host {
			host = component
		}
	}
	s.WriteString(")\n")
	if !toolchain {
		for i := range m.Application.Packs {
			fmt.Fprintf(&s, "//go:embed packs/%d.wapp\nvar pack%d []byte\n", i, i)
		}
	}
	s.WriteString("func main() {\n")
	for i, n := range m.Native {
		fmt.Fprintf(&s, "component%d := native%d.%s()\n", i, i, n.Factory)
	}
	if toolchain {
		s.WriteString(`directory, err := os.Getwd()
 if err != nil { fmt.Fprintln(os.Stderr, err); os.Exit(1) }
 config := []string{}
 if _, err := os.Stat(filepath.Join(directory, ".wippy.yaml")); err == nil {
 config = append(config, filepath.Join(directory, ".wippy.yaml"))
 } else if !os.IsNotExist(err) { fmt.Fprintln(os.Stderr, err); os.Exit(1) }
 err = cmd.ExecuteWithOptions(context.Background(), cmd.ExecuteOptions{
 Args: os.Args[1:], LockFile: filepath.Join(directory, "wippy.lock"), ConfigFiles: config,
 `)
		fmt.Fprintf(&s, "Components: []boot.Component{%s},\n})\n", strings.Join(components, ","))
		s.WriteString("if err != nil { fmt.Fprintln(os.Stderr, err); os.Exit(1) }\n")
	} else {
		app := m.Application
		fmt.Fprintf(&s, "app.Main(app.Executable{Name: %q, Command: %q, Host: %s,\nComponents: []boot.Component{%s},\nData: map[string]string{", m.Name, app.Command, host, strings.Join(components, ","))
		keys := make([]string, 0, len(app.Data))
		for k := range app.Data {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		for _, k := range keys {
			fmt.Fprintf(&s, "%s:%s,", strconv.Quote(k), strconv.Quote(app.Data[k]))
		}
		fmt.Fprintf(&s, "},\nBundle: app.Bundle{Root: %q, Packs: []app.Pack{", app.Module)
		for i, p := range app.Packs {
			fmt.Fprintf(&s, "{Module:%q,Version:%q,Digest:%q,Data:pack%d},", p.Module, p.Version, "sha256:"+p.SHA256, i)
		}
		s.WriteString("}},\n})\n")
	}
	s.WriteString("}\n")
	return format.Source([]byte(s.String()))
}
