// SPDX-License-Identifier: MIT
package assemble

import (
	"fmt"
	"go/format"
	"sort"
	"strconv"
	"strings"
)

func Generate(m *Manifest, toolchain bool) ([]byte, error) {
	return generate(m, toolchain, "github.com/wippyai/runtime/cmd/app")
}

func generate(m *Manifest, toolchain bool, applicationPackage string) ([]byte, error) {
	var s strings.Builder
	s.WriteString("// Code generated by Wippy Builder. DO NOT EDIT.\n// SPDX-License-Identifier: MIT\npackage main\nimport (\n\"context\"\n\"fmt\"\n\"os\"\n\"github.com/wippyai/runtime/api/boot\"\n")
	if toolchain {
		s.WriteString("\"path/filepath\"\n\"github.com/wippyai/runtime/cmd/wippy/cmd\"\n")
	} else {
		fmt.Fprintf(&s, "_ \"embed\"\napplication %q\n", applicationPackage)
	}
	var factories []string
	packageAliases := map[string]string{}
	var packages []string
	for i, n := range m.Native {
		alias, exists := packageAliases[n.Package]
		if !exists {
			alias = fmt.Sprintf("native%d", len(packages))
			packageAliases[n.Package] = alias
			packages = append(packages, n.Package)
		}
		factories = append(factories, fmt.Sprintf("component%d", i))
	}
	for i, packagePath := range packages {
		fmt.Fprintf(&s, "native%d %q\n", i, packagePath)
	}
	s.WriteString(")\n")
	if !toolchain {
		for i := range m.Application.Packs {
			fmt.Fprintf(&s, "//go:embed packs/%d.wapp\nvar pack%d []byte\n", i, i)
		}
	}
	s.WriteString("func main() {\n")
	for i, n := range m.Native {
		fmt.Fprintf(&s, "component%d := %s.%s()\n", i, packageAliases[n.Package], n.Factory)
	}
	if toolchain {
		s.WriteString(`directory, err := os.Getwd()
 if err != nil { fmt.Fprintln(os.Stderr, err); os.Exit(1) }
 config := []string{}
 if _, err := os.Stat(filepath.Join(directory, ".wippy.yaml")); err == nil {
 config = append(config, filepath.Join(directory, ".wippy.yaml"))
 } else if !os.IsNotExist(err) { fmt.Fprintln(os.Stderr, err); os.Exit(1) }
 err = cmd.ExecuteWithOptions(context.Background(), cmd.ExecuteOptions{
 Args: os.Args[1:], LockFile: filepath.Join(directory, "wippy.lock"), ConfigFiles: config,
 `)
		fmt.Fprintf(&s, "Components: []boot.Component{%s},\n})\n", strings.Join(factories, ","))
	} else {
		app := m.Application
		fmt.Fprintf(&s, "err := application.Run(context.Background(), application.Options{Name: %q, Command: %q, Mode: %q,\nComponents: []boot.Component{%s},\n", m.Name, app.Command, app.Mode, strings.Join(factories, ","))
		if app.Baseline != "" {
			fmt.Fprintf(&s, "Baseline: %q,\n", app.Baseline)
		}
		for i, n := range m.Native {
			if n.Launch {
				fmt.Fprintf(&s, "Launch: component%d.Launch,\nDefaultStateDir: component%d.DefaultStateDir,\n", i, i)
			}
		}
		s.WriteString("DataEnv: map[string]string{")
		keys := make([]string, 0, len(app.DataEnv))
		for k := range app.DataEnv {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		for _, k := range keys {
			fmt.Fprintf(&s, "%s:%s,", strconv.Quote(k), strconv.Quote(app.DataEnv[k]))
		}
		fmt.Fprintf(&s, "},\nBundle: application.Bundle{Root: %q, Packs: []application.Pack{", app.Module)
		for i, p := range app.Packs {
			fmt.Fprintf(&s, "{Module:%q,Version:%q,Digest:%q,Data:pack%d},", p.Module, p.Version, "sha256:"+p.SHA256, i)
		}
		s.WriteString("}},\n}, os.Args[1:])\n")
	}
	s.WriteString("if err != nil { fmt.Fprintln(os.Stderr, err); os.Exit(1) }\n}\n")
	return format.Source([]byte(s.String()))
}
