// SPDX-License-Identifier: MIT
package assemble

import (
	"fmt"
	"go/format"
	"sort"
	"strconv"
	"strings"
)

func Generate(m *Manifest, toolchain bool) ([]byte, error) {
	return generate(m, toolchain, "")
}

// GenerateWithLuaCacheSeed emits an application entrypoint that embeds the
// validated cache archive at lua-cache.seed.
func GenerateWithLuaCacheSeed(m *Manifest, digest string) ([]byte, error) {
	if digest == "" {
		return nil, fmt.Errorf("Lua cache seed digest is required")
	}
	return generate(m, false, digest)
}

func generate(m *Manifest, toolchain bool, cacheDigest string) ([]byte, error) {
	var s strings.Builder
	s.WriteString("// Code generated by Wippy Builder. DO NOT EDIT.\n// SPDX-License-Identifier: MIT\npackage main\nimport (\n\"github.com/wippyai/runtime/api/boot\"\n")
	if toolchain {
		s.WriteString("\"context\"\n\"fmt\"\n\"os\"\n\"path/filepath\"\n\"github.com/wippyai/runtime/cmd/wippy/cmd\"\n")
	} else {
		s.WriteString("_ \"embed\"\n\"github.com/wippyai/runtime/cmd/app\"\n")
		if cacheDigest != "" {
			s.WriteString("\"fmt\"\n\"os\"\n")
		}
	}
	var factories []string
	for i, n := range m.Native {
		fmt.Fprintf(&s, "native%d %q\n", i, n.Package)
		factories = append(factories, fmt.Sprintf("native%d.%s()", i, n.Factory))
	}
	s.WriteString(")\n")
	if !toolchain {
		for i := range m.Application.Packs {
			fmt.Fprintf(&s, "//go:embed packs/%d.wapp\nvar pack%d []byte\n", i, i)
		}
		if cacheDigest != "" {
			s.WriteString("//go:embed lua-cache.seed\nvar luaCacheSeed []byte\n")
		}
	}
	s.WriteString("func main() {\n")
	if toolchain {
		s.WriteString(`directory, err := os.Getwd()
 if err != nil { fmt.Fprintln(os.Stderr, err); os.Exit(1) }
 config := []string{}
 if _, err := os.Stat(filepath.Join(directory, ".wippy.yaml")); err == nil {
 config = append(config, filepath.Join(directory, ".wippy.yaml"))
 } else if !os.IsNotExist(err) { fmt.Fprintln(os.Stderr, err); os.Exit(1) }
 err = cmd.ExecuteWithOptions(context.Background(), cmd.ExecuteOptions{
 Args: os.Args[1:], LockFile: filepath.Join(directory, "wippy.lock"), ConfigFiles: config,
 `)
		fmt.Fprintf(&s, "Components: []boot.Component{%s},\n})\n", strings.Join(factories, ","))
		s.WriteString("if err != nil { fmt.Fprintln(os.Stderr, err); os.Exit(1) }\n")
	} else {
		if cacheDigest != "" {
			s.WriteString("schema, toolchainID, identityErr := app.LuaCacheIdentity()\nif identityErr != nil { fmt.Fprintln(os.Stderr, identityErr); os.Exit(1) }\n")
		}
		app := m.Application
		fmt.Fprintf(&s, "app.Main(app.Executable{Name: %q, Command: %q,\nComponents: []boot.Component{%s},\nData: map[string]string{", m.Name, app.Command, strings.Join(factories, ","))
		keys := make([]string, 0, len(app.DataEnv))
		for k := range app.DataEnv {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		for _, k := range keys {
			fmt.Fprintf(&s, "%s:%s,", strconv.Quote(k), strconv.Quote(app.DataEnv[k]))
		}
		fmt.Fprintf(&s, "},\nBundle: app.Bundle{Root: %q, Packs: []app.Pack{", app.Module)
		for i, p := range app.Packs {
			fmt.Fprintf(&s, "{Module:%q,Version:%q,Digest:%q,Data:pack%d},", p.Module, p.Version, "sha256:"+p.SHA256, i)
		}
		s.WriteString("}}")
		if cacheDigest != "" {
			fmt.Fprintf(&s, ",\nLuaCacheSeed: &app.LuaCacheSeed{Archive:luaCacheSeed,Digest:%q,SchemaVersion:schema,ToolchainIdentity:toolchainID}", cacheDigest)
		}
		s.WriteString(",\n})\n")
	}
	s.WriteString("}\n")
	return format.Source([]byte(s.String()))
}
